language: ruby
rvm:
  - 1.9.3
  - 2.0.0
services:
  - mongodb

before_script:
  - psql -c 'create database travis_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis
  - psql -f test_data.sql -U postgres -d travis_postgis

script: rspec .
